services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: civicrm-postgres
    environment:
      POSTGRES_DB: civicrm
      POSTGRES_USER: civicrm
      POSTGRES_PASSWORD: civicrm_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U civicrm -d civicrm"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: civicrm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis_dev_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: civicrm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@civicrm.dev
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/pgadmin-servers.json:/pgadmin4/servers.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - tools

  # Redocly API documentation server
  # redocly:
  #   image: nginx:alpine
  #   container_name: civicrm-redocly
  #   ports:
  #     - "8082:80"
  #   volumes:
  #     - ./internal/api/static:/usr/share/nginx/html:ro
  #     - ./api/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
  #   command: >
  #     sh -c "echo 'server { 
  #       listen 80; 
  #       root /usr/share/nginx/html; 
  #       index docs.html; 
  #       location / { 
  #         try_files $$uri $$uri/ /docs.html; 
  #       } 
  #       location /openapi.yaml { 
  #         add_header Access-Control-Allow-Origin *; 
  #       }
  #     }' > /etc/nginx/conf.d/default.conf &&
  #     nginx -g 'daemon off;'"
  #   restart: unless-stopped
  #   profiles:
  #     - tools


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: civicrm-network
