//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExtensionStatus.
const (
	Active   ExtensionStatus = "active"
	Error    ExtensionStatus = "error"
	Inactive ExtensionStatus = "inactive"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// APIInfo defines model for APIInfo.
type APIInfo struct {
	Description *string   `json:"description,omitempty"`
	Entities    *[]string `json:"entities,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Version     *string   `json:"version,omitempty"`
}

// APIResponse defines model for APIResponse.
type APIResponse struct {
	// Count Number of records returned
	Count        *int                      `json:"count,omitempty"`
	ErrorCode    *string                   `json:"error_code,omitempty"`
	ErrorMessage *string                   `json:"error_message,omitempty"`
	IsError      *bool                     `json:"is_error,omitempty"`
	Values       *[]map[string]interface{} `json:"values,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// ErrorCode Machine-readable error code
	ErrorCode *string `json:"error_code,omitempty"`

	// ErrorData Additional error context
	ErrorData *map[string]interface{} `json:"error_data,omitempty"`

	// ErrorMessage Human-readable error message
	ErrorMessage *string `json:"error_message,omitempty"`
	IsError      *bool   `json:"is_error,omitempty"`
}

// Extension defines model for Extension.
type Extension struct {
	// Description Extension description
	Description *string `json:"description,omitempty"`

	// Name Extension name
	Name *string `json:"name,omitempty"`

	// Status Extension status
	Status *ExtensionStatus `json:"status,omitempty"`

	// Version Extension version
	Version *string `json:"version,omitempty"`
}

// ExtensionStatus Extension status
type ExtensionStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    *HealthResponseStatus `json:"status,omitempty"`
	Timestamp *time.Time            `json:"timestamp,omitempty"`

	// Uptime Service uptime in human-readable format
	Uptime  *string `json:"uptime,omitempty"`
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// EntityDeleteParams defines parameters for EntityDelete.
type EntityDeleteParams struct {
	// Id Entity ID to delete
	Id string `form:"id" json:"id"`
}

// EntityGetParams defines parameters for EntityGet.
type EntityGetParams struct {
	// Id Entity ID for single entity retrieval
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// Select Comma-separated list of fields to select
	Select *string `form:"select,omitempty" json:"select,omitempty"`

	// Where JSON string of where conditions
	Where *string `form:"where,omitempty" json:"where,omitempty"`

	// OrderBy JSON string of order by clauses
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`

	// Limit Maximum number of records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of records to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// EntityCreateJSONBody defines parameters for EntityCreate.
type EntityCreateJSONBody map[string]interface{}

// EntityUpdateJSONBody defines parameters for EntityUpdate.
type EntityUpdateJSONBody map[string]interface{}

// EntityUpdateParams defines parameters for EntityUpdate.
type EntityUpdateParams struct {
	// Id Entity ID to update
	Id string `form:"id" json:"id"`
}

// EntityCreateJSONRequestBody defines body for EntityCreate for application/json ContentType.
type EntityCreateJSONRequestBody EntityCreateJSONBody

// EntityUpdateJSONRequestBody defines body for EntityUpdate for application/json ContentType.
type EntityUpdateJSONRequestBody EntityUpdateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get API information
	// (GET /)
	ApiInfo(w http.ResponseWriter, r *http.Request)
	// List extensions
	// (GET /extensions)
	ListExtensions(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Delete entity
	// (DELETE /{entity}/{action})
	EntityDelete(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityDeleteParams)
	// Get entities
	// (GET /{entity}/{action})
	EntityGet(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityGetParams)
	// Create entity
	// (POST /{entity}/{action})
	EntityCreate(w http.ResponseWriter, r *http.Request, entity string, action string)
	// Update entity
	// (PUT /{entity}/{action})
	EntityUpdate(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityUpdateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApiInfo operation middleware
func (siw *ServerInterfaceWrapper) ApiInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApiInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExtensions operation middleware
func (siw *ServerInterfaceWrapper) ListExtensions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExtensions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityDelete operation middleware
func (siw *ServerInterfaceWrapper) EntityDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityDeleteParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityDelete(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityGet operation middleware
func (siw *ServerInterfaceWrapper) EntityGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityGetParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Optional query parameter "select" -------------

	err = runtime.BindQueryParameter("form", true, false, "select", r.URL.Query(), &params.Select)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "select", Err: err})
		return
	}

	// ------------- Optional query parameter "where" -------------

	err = runtime.BindQueryParameter("form", true, false, "where", r.URL.Query(), &params.Where)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "where", Err: err})
		return
	}

	// ------------- Optional query parameter "orderBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderBy", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderBy", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityGet(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityCreate operation middleware
func (siw *ServerInterfaceWrapper) EntityCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityCreate(w, r, entity, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityUpdate operation middleware
func (siw *ServerInterfaceWrapper) EntityUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityUpdateParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityUpdate(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.ApiInfo)
	m.HandleFunc("GET "+options.BaseURL+"/extensions", wrapper.ListExtensions)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)
	m.HandleFunc("DELETE "+options.BaseURL+"/{entity}/{action}", wrapper.EntityDelete)
	m.HandleFunc("GET "+options.BaseURL+"/{entity}/{action}", wrapper.EntityGet)
	m.HandleFunc("POST "+options.BaseURL+"/{entity}/{action}", wrapper.EntityCreate)
	m.HandleFunc("PUT "+options.BaseURL+"/{entity}/{action}", wrapper.EntityUpdate)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RY328TORD+VyzfSYC0JOHoU97a0oMg2qta0D2gCjnrSWLYtRd7HBpV+d9P/rGbbNYb",
	"iICAdC/tZj32N/N55ht7H2iuykpJkGjo+IGafAEl84+n15OJnCn3WGlVgUYBfoCDybWoUCjpfsI9K6sC",
	"6Jiei6U4v7kkNxe3b8np9YQsT2hGcVW5QYNayDldZxQkinqtZvJ7eq4kshxp5p+0mFqPkNGLJUj3+hLK",
	"KWizEBW9y6hAKP0SnfXjC6Y1W7nfkpWQdrTfxyVo04nvZDAajLrWG0g1/Qg5uvmn15MbMJWSBroE5spK",
	"7DBJr6yLj6gZ0ZArzQ3RgFZL4BtMIRHmoD2NWiv9IVcckiyE4RKMYfO0hTAfvFEryBkrDDRwU6UKYNIz",
	"wgob3G+YZ5wL5zsrrrfiQ20hwUh7V1KcXThn+llrx9um7pLlCyHhqQbG2bQA4o2JN876uOEM2dfCaMOc",
	"NpYNgES4R5qIpsN/e6lXtmRy19/aOvvGzWpR3exVktt7BFln9N5ybrvZzCPb7xP+1UXWN92PJ+YZZGjN",
	"vpnRwumGLZ1QsBzF0i0mZPMYuLnbX8l9CLXJN1X2K2AFLvrTdBNQ7e/Cz1jRjFpZP6c8RVGCQVZWbvJM",
	"6ZIhHVPOEJ66oRR7tvIjndhuQS9FDiSMEyHJop1vcfn9fH2VDbd/kFstcHXrGkdg4AyYBn1qceF+Tf2v",
	"v+twXv/7lmahzfik9aMbPxaIFV27hUXsPXlsC+OHmGONer8FVjpSdREnmvFwmIulyHU5UNpH06Yl0aCI",
	"qSAXM5GzOrMFpntEQ0zsA+uMqgokqwQd0+eD0eA5zWjFcOFJGLo/c0jI/I0XdUNcgI4Ul4FsqiwSXADp",
	"wLrc8kYT7hSoEr4pZ1THDPRof41GNVcQWgurqiIGNfxown6G5u6e/tQwo2P6x3DT/Yex9Q/rvu93YUf/",
	"rifbbocEsGXJ9IqO6UtAkrIYQl1pppcUN7cQBl33KxTjwMnWrF0W3giDF9vD30VG08/2sbIR0G4v6/D0",
	"JkayFUKbKm+wMzoM2tBL0fkC8k9EzHyamFjgwpCNvLRJCkLlZ/3MdNnRwwQbt11f22yEJUjuXfVUPPgz",
	"4mo9fHAKr+Q60FEAJsTuhX9PmCRhVoeJC/86mPka1awEBG3o+H2nK3hb4nfYiRAd+5qmdYejDYaGz1Zo",
	"4HUb3tDV0c1dkFMfFHlsjWVFsSKPQmiPnqQhAwffBxnjmrwgqAivqfBgny3o1QZN8IOQ7n6uFO1LrBhT",
	"iIa7wjwZnfww8PZxtB9eKiQzZSXfyeqYljFf1llvN9ACltFOgHG64Ss89CXgdS6mcvol4AEJTR7DYD7I",
	"SLxphYf6opURf8968tOzHhWpQLsWUfszB8xIroEhZMRW3P8Pu3qUipgpTYyQ86LeLXfxcrvCin01cgDW",
	"uSpL9tSA2ykE3rS6mYCCG0eJgQL85TcF1wweAPn69p8rEoYd0pcFaHD3lXCDMT1I3uy7gJTmoMl0RfKC",
	"WacJaSBvdrY6DOqS3YvSlkR2bsqo4mW5B64QpWgTWIa16PjZaDTKaClk/Nm9a3cduUo5YD6Jqi/a2czA",
	"Dn4NOEoA/kJRvbV5DsYENR0dT03PGCeumsHg0ZX8qkfC3am0+Vq1zmilTOpg5pWLMCLhSy0gh4h4mP97",
	"HkyCKv/Ag8ldMAaDZ4qvDtriAz43uW1s+7TuVNSzIx9TApX81xZWK71j4m5OKJVNpPc735D98fpeGHQy",
	"v/ecHex/z3QOh4ujnbNtTcWPOmf/FoVz7PN9YJH/rzrSV+4WsSbryt3+EOdrbfsT3Ps7lzsG9DJdifE7",
	"2JQZIO9u3jRf1IasEsPlCV3frf8LAAD//8WX7lUmGgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
