//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ExtensionStatus.
const (
	Active   ExtensionStatus = "active"
	Error    ExtensionStatus = "error"
	Inactive ExtensionStatus = "inactive"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// APIInfo defines model for APIInfo.
type APIInfo struct {
	Description *string   `json:"description,omitempty"`
	Entities    *[]string `json:"entities,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Version     *string   `json:"version,omitempty"`
}

// APIResponse defines model for APIResponse.
type APIResponse struct {
	// Count Number of records returned
	Count        *int                      `json:"count,omitempty"`
	ErrorCode    *string                   `json:"error_code,omitempty"`
	ErrorMessage *string                   `json:"error_message,omitempty"`
	IsError      *bool                     `json:"is_error,omitempty"`
	Values       *[]map[string]interface{} `json:"values,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// ErrorCode Machine-readable error code
	ErrorCode *string `json:"error_code,omitempty"`

	// ErrorData Additional error context
	ErrorData *map[string]interface{} `json:"error_data,omitempty"`

	// ErrorMessage Human-readable error message
	ErrorMessage *string `json:"error_message,omitempty"`
	IsError      *bool   `json:"is_error,omitempty"`
}

// Extension defines model for Extension.
type Extension struct {
	// Description Extension description
	Description *string `json:"description,omitempty"`

	// Name Extension name
	Name *string `json:"name,omitempty"`

	// Status Extension status
	Status *ExtensionStatus `json:"status,omitempty"`

	// Version Extension version
	Version *string `json:"version,omitempty"`
}

// ExtensionStatus Extension status
type ExtensionStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status    *HealthResponseStatus `json:"status,omitempty"`
	Timestamp *time.Time            `json:"timestamp,omitempty"`

	// Uptime Service uptime in human-readable format
	Uptime  *string `json:"uptime,omitempty"`
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// EntityDeleteParams defines parameters for EntityDelete.
type EntityDeleteParams struct {
	// Id Entity ID to delete
	Id string `form:"id" json:"id"`
}

// EntityGetParams defines parameters for EntityGet.
type EntityGetParams struct {
	// Id Entity ID for single entity retrieval
	Id *string `form:"id,omitempty" json:"id,omitempty"`

	// Select Comma-separated list of fields to select
	Select *string `form:"select,omitempty" json:"select,omitempty"`

	// Where JSON string of where conditions
	Where *string `form:"where,omitempty" json:"where,omitempty"`

	// OrderBy JSON string of order by clauses
	OrderBy *string `form:"orderBy,omitempty" json:"orderBy,omitempty"`

	// Limit Maximum number of records to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of records to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// EntityCreateJSONBody defines parameters for EntityCreate.
type EntityCreateJSONBody map[string]interface{}

// EntityUpdateJSONBody defines parameters for EntityUpdate.
type EntityUpdateJSONBody map[string]interface{}

// EntityUpdateParams defines parameters for EntityUpdate.
type EntityUpdateParams struct {
	// Id Entity ID to update
	Id string `form:"id" json:"id"`
}

// EntityCreateJSONRequestBody defines body for EntityCreate for application/json ContentType.
type EntityCreateJSONRequestBody EntityCreateJSONBody

// EntityUpdateJSONRequestBody defines body for EntityUpdate for application/json ContentType.
type EntityUpdateJSONRequestBody EntityUpdateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get API information
	// (GET /)
	ApiInfo(w http.ResponseWriter, r *http.Request)
	// List extensions
	// (GET /extensions)
	ListExtensions(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// Serve static assets
	// (GET /static/{path})
	ServeStatic(w http.ResponseWriter, r *http.Request, path string)
	// Delete entity
	// (DELETE /{entity}/{action})
	EntityDelete(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityDeleteParams)
	// Get entities
	// (GET /{entity}/{action})
	EntityGet(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityGetParams)
	// Create entity
	// (POST /{entity}/{action})
	EntityCreate(w http.ResponseWriter, r *http.Request, entity string, action string)
	// Update entity
	// (PUT /{entity}/{action})
	EntityUpdate(w http.ResponseWriter, r *http.Request, entity string, action string, params EntityUpdateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ApiInfo operation middleware
func (siw *ServerInterfaceWrapper) ApiInfo(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApiInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListExtensions operation middleware
func (siw *ServerInterfaceWrapper) ListExtensions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListExtensions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ServeStatic operation middleware
func (siw *ServerInterfaceWrapper) ServeStatic(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "path" -------------
	var path string

	err = runtime.BindStyledParameterWithOptions("simple", "path", r.PathValue("path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ServeStatic(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityDelete operation middleware
func (siw *ServerInterfaceWrapper) EntityDelete(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityDeleteParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityDelete(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityGet operation middleware
func (siw *ServerInterfaceWrapper) EntityGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityGetParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Optional query parameter "select" -------------

	err = runtime.BindQueryParameter("form", true, false, "select", r.URL.Query(), &params.Select)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "select", Err: err})
		return
	}

	// ------------- Optional query parameter "where" -------------

	err = runtime.BindQueryParameter("form", true, false, "where", r.URL.Query(), &params.Where)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "where", Err: err})
		return
	}

	// ------------- Optional query parameter "orderBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "orderBy", r.URL.Query(), &params.OrderBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderBy", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityGet(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityCreate operation middleware
func (siw *ServerInterfaceWrapper) EntityCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityCreate(w, r, entity, action)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EntityUpdate operation middleware
func (siw *ServerInterfaceWrapper) EntityUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "entity" -------------
	var entity string

	err = runtime.BindStyledParameterWithOptions("simple", "entity", r.PathValue("entity"), &entity, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity", Err: err})
		return
	}

	// ------------- Path parameter "action" -------------
	var action string

	err = runtime.BindStyledParameterWithOptions("simple", "action", r.PathValue("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params EntityUpdateParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EntityUpdate(w, r, entity, action, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/{$}", wrapper.ApiInfo)
	m.HandleFunc("GET "+options.BaseURL+"/extensions", wrapper.ListExtensions)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)
	m.HandleFunc("GET "+options.BaseURL+"/static/{path}", wrapper.ServeStatic)
	m.HandleFunc("DELETE "+options.BaseURL+"/{entity}/{action}", wrapper.EntityDelete)
	m.HandleFunc("GET "+options.BaseURL+"/{entity}/{action}", wrapper.EntityGet)
	m.HandleFunc("POST "+options.BaseURL+"/{entity}/{action}", wrapper.EntityCreate)
	m.HandleFunc("PUT "+options.BaseURL+"/{entity}/{action}", wrapper.EntityUpdate)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYXW/UOhP+K5bfVwKk0CyHXu1dWwoU0Z6qBZ0LVCFvPNkYYjvYk6Wrav/7ke0ku9k4",
	"W5aPgnRu2mw845l5/MxHfEczLSutQKGl0ztqswIk849Hl2dnKtfusTK6AoMC/AIHmxlRodDK/YRbJqsS",
	"6JSeiIU4uTonV6fX78jR5RlZHNKE4rJyixaNUHO6SigoFO1enfIHeqIVsgxp4p+MmNXeQkJPF6Dc63OQ",
	"MzC2EBW9SahAkH6Lwf7NC2YMW7rfikmIOzru4wKMHcR3eDA5mAyl1yb17BNk6PSPLs+uwFZaWRgCmOla",
	"4QBJelG7+IjOiYFMG26JAayNAr62KRTCHIyH0RhtPmaaQxSFsCzBWjaPSwj70Qv1gsxZaaEzN9O6BKY8",
	"Iqysg/sd8oxz4Xxn5eVGfGhqiCDSP5UYZqfOmXHU+vH2oTtnWSEUPDXAOJuVQLww8cLJGDacIbsvjL6Z",
	"o06yM6AQbpFGohng39/qdS2Z2va3lU6+8bB6UHdnFcX2FkG1jN6Zzn03Oz2y+T7iX5tkY+p+PaJnkWFt",
	"d2k2Eq5u1NIVCpahWLjNhOoeAzY3uzN5zEIr8k2Z/RpYicU4TdcBtf4WXmNJE1qr9jnmKQoJFpmsnHKu",
	"jWRIp5QzhKduKYZeXfmVQWzXYBYiAxLWiVCk6POt2X43Xvei4c4PstoIXF67xhEQOAZmwBzVWLhfM//r",
	"ZRvOm3/e0SS0GU9av7r2o0Cs6MptLJrekzVtYXrXcKyr3u+ASQeqKRtFO03TTCxEZuSBNj6aPiyRBkVs",
	"BZnIRcZaZguM94gOmKYPrBKqK1CsEnRKnx9MDp7ThFYMCw9C6v7MIVLmr3xRt8QF6EBxDGQzXSPBAsjA",
	"rOOWFzrjrgJVwjflhJqGgd7aX5NJixWE1sKqqmyCSj/ZcJ6hubun/xvI6ZT+L113/7Rp/Wnb9/0pbNW/",
	"y7NNtwMBaimZWdIpfQVIYhIptJlmR0FxuqWw6LpfqRkHTja0tlF4Kyyebi7/EBhdP9uFyrqADnvZAKe3",
	"TSQbIfSh8gJbq2moDaMQnRSQfSYi9zSxTYILS9blpQ9SKFRe61fSZaseRtC4HvraRyNsQTLvqofCFVGR",
	"pXcunVajiLiNgQRZkosSLMmNlh4gNytyRyP3ntilRZADiPwG117f565hEhCMpdMP27YuGRYEdQB/bdF3",
	"ITr1eU/bLtj+MvClFgZ426jXgG5X1pv9DogtWPCtf0zDei0km0M6F3lfsGsuM6HcESSjqp8qmH+vbqW+",
	"Q9WNU2lm7X2RebkCZblbcEjG9dmRFt5VQg8nh0N+vXRCSiPJda34Fml75GPWAjZpfOe/b5ar9M5NJ1qt",
	"wsYlYKRRv/DvCVMkaA0oeupfB7H7OBpkiccgysvOxrczM9k2cuSDIo9rW7OyXJJHIbRHT+ImAwY/ZrKJ",
	"6+yFS0DeQuGNfanBE6mxJvivTLt92+iuotjEFKLhGxT8Kcb7n1Lj5sfI3dCy4csqGZ1kjIBFIyfAup7n",
	"C2SYqYC3XIxx+hXgHoQmj+FgfpCQ5pYgPLSXBAnxdwRPfjnrUZMKjKtjrT9zwIRkBhhCQuqK+//hVB8k",
	"I3JtiBVqXranRUw4FVbuypE9bJ1oKdlTC+6kEHg3puUCSm4dJBZK8Bc3MXPd4h4m31z/fUHCsrP0tQDj",
	"q3X4+rYjlrzYDxnShoMhsyXJSla7mhA35MWOl/uZOme3QtaSqMEtD+rmomfEXCmk6AMow150+mwymSRU",
	"CtX8HN4TDR25iDlgP4tqLNo8t7BlvzU4iRj8jUX1us4ysDZU08nDVdNjxonLZrD44JX8YqSEuy+q7qZ1",
	"ldBK29hHha9chBEFX9sCsk8RD/p/5mASqvJPHExugjBYPNZ8udcR73FV6o6x79NqkFHPHnhMCVDy35tY",
	"PXo3xF1PKFUdofd735D9eH0rLLoyv3PODvJ/Jp3DcPFgc3bdQvGz5uw/InEeer4PKPL/VEe659uiyck2",
	"czcvkX2ubV4ff7hx3LHuUzuaic0d7oxZIO+v3na3wSmrRLo4pKub1b8BAAD//5jIX1jiHAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
